export const FETCH_TODO_REQUEST = "FETCH_TODO_REQUEST";
export const FETCH_TODO_SUCCESS = "FETCH_TODO_SUCCESS";
export const FETCH_TODO_FAILURE = "FETCH_TODO_FAILURE";

export const SEARCH_ACTION = "SEARCH_ACTION";

export const SINGLE_NFT_REQUEST = "SINGLE_NFT_REQUEST";
export const SINGLE_NFT_SUCCESS = "SINGLE_NFT_SUCCESS";
export const SINGLE_NFT_FAILURE = "SINGLE_NFT_FAILURE";
