export const FETCH_NFTS_REQUEST = "FETCH_NFTS_REQUEST";
export const FETCH_NFTS_SUCCESS = "FETCH_NFTS_SUCCESS";

export const SEARCH_ACTION = "SEARCH_ACTION";

export const SINGLE_NFT_REQUEST = "SINGLE_NFT_REQUEST";
export const SINGLE_NFT_SUCCESS = "SINGLE_NFT_SUCCESS";

export const SET_SCROLL_POSITION = "SET_SCROLL_POSITION";